# test-golangci-lint configuration file for golangci-lint

run:
  skip-files:
    - lang/lexer.nn.go
    - lang/y.go
    - bindata/bindata.go
    - lang/types/kind_stringer.go
    - lang/interpolate/parse.generated.go
    - lang/interpolate/interpolate/parse.generated.go

linters:
  disable-all: true
  enable:
    - goimports
    - revive
    - misspell

