#!/bin/bash

# Stop on any error
set -e

script_directory="$( cd "$( dirname "$0" )" && pwd )"
project_directory=$script_directory/../..

# Specify the Docker image name
image_name='purpleidea/mgmt:development'

# Run container in development mode
docker run --rm --name=mgm_development --user=mgmt \
	-v $project_directory:/home/mgmt/mgmt \
	-it $image_name bash
