// Mgmt
// Copyright (C) James Shubin and the project contributors
// Written by James Shubin <james@shubin.ca> and the project contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Additional permission under GNU GPL version 3 section 7
//
// If you modify this program, or any covered work, by linking or combining it
// with embedded mcl code and modules (and that the embedded mcl code and
// modules which link with this program, contain a copy of their source code in
// the authoritative form) containing parts covered by the terms of any other
// license, the licensors of this program grant you additional permission to
// convey the resulting work. Furthermore, the licensors of this program grant
// the original author, James Shubin, additional permission to update this
// additional permission if he deems it necessary to achieve the goals of this
// additional permission.

// Code generated by goyacc -v parser/y.output -o parser/y.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:31
package parser

import (
	"fmt"
	__yyfmt__ "fmt"
	"strings"

	"github.com/purpleidea/mgmt/lang/ast"
	"github.com/purpleidea/mgmt/lang/funcs"
	"github.com/purpleidea/mgmt/lang/funcs/operators"
	"github.com/purpleidea/mgmt/lang/interfaces"
	"github.com/purpleidea/mgmt/lang/types"
	"github.com/purpleidea/mgmt/util"
) //line parser/parser.y:31

const (
	errstrParseAdditionalEquals = "additional equals in bind statement"
	errstrParseExpectingComma   = "expecting trailing comma"
)

func init() {
	yyErrorVerbose = true // set the global that enables showing full errors
}

//line parser/parser.y:55
type yySymType struct {
	yys int
	row int
	col int

	endRow int
	endCol int

	//err error // TODO: if we ever match ERROR in the parser

	bool  bool
	str   string
	int   int64 // this is the .int as seen in lexer.nex
	float float64

	typ *types.Type

	stmts []interfaces.Stmt
	stmt  interfaces.Stmt

	exprs []interfaces.Expr
	expr  interfaces.Expr

	mapKVs []*ast.ExprMapKV
	mapKV  *ast.ExprMapKV

	structFields []*ast.ExprStructField
	structField  *ast.ExprStructField

	args []*interfaces.Arg
	arg  *interfaces.Arg

	resContents []ast.StmtResContents // interface
	resField    *ast.StmtResField
	resEdge     *ast.StmtResEdge
	resMeta     *ast.StmtResMeta

	edgeHalfList []*ast.StmtEdgeHalf
	edgeHalf     *ast.StmtEdgeHalf
}

const NEWLINE = 57346
const OPEN_CURLY = 57347
const CLOSE_CURLY = 57348
const OPEN_PAREN = 57349
const CLOSE_PAREN = 57350
const OPEN_BRACK = 57351
const CLOSE_BRACK = 57352
const IF = 57353
const ELSE = 57354
const FOR = 57355
const FORKV = 57356
const BOOL = 57357
const STRING = 57358
const INTEGER = 57359
const FLOAT = 57360
const EQUALS = 57361
const DOLLAR = 57362
const COMMA = 57363
const COLON = 57364
const SEMICOLON = 57365
const ELVIS = 57366
const DEFAULT = 57367
const ROCKET = 57368
const ARROW = 57369
const DOT = 57370
const BOOL_IDENTIFIER = 57371
const STR_IDENTIFIER = 57372
const INT_IDENTIFIER = 57373
const FLOAT_IDENTIFIER = 57374
const MAP_IDENTIFIER = 57375
const STRUCT_IDENTIFIER = 57376
const VARIANT_IDENTIFIER = 57377
const IDENTIFIER = 57378
const CAPITALIZED_IDENTIFIER = 57379
const FUNC_IDENTIFIER = 57380
const CLASS_IDENTIFIER = 57381
const INCLUDE_IDENTIFIER = 57382
const IMPORT_IDENTIFIER = 57383
const AS_IDENTIFIER = 57384
const COMMENT = 57385
const ERROR = 57386
const COLLECT_IDENTIFIER = 57387
const PANIC_IDENTIFIER = 57388
const OR = 57389
const AND = 57390
const LT = 57391
const GT = 57392
const LTE = 57393
const GTE = 57394
const EQ = 57395
const NEQ = 57396
const IN = 57397
const PLUS = 57398
const MINUS = 57399
const MULTIPLY = 57400
const DIVIDE = 57401
const NOT = 57402

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NEWLINE",
	"OPEN_CURLY",
	"CLOSE_CURLY",
	"OPEN_PAREN",
	"CLOSE_PAREN",
	"OPEN_BRACK",
	"CLOSE_BRACK",
	"IF",
	"ELSE",
	"FOR",
	"FORKV",
	"BOOL",
	"STRING",
	"INTEGER",
	"FLOAT",
	"EQUALS",
	"DOLLAR",
	"COMMA",
	"COLON",
	"SEMICOLON",
	"ELVIS",
	"DEFAULT",
	"ROCKET",
	"ARROW",
	"DOT",
	"BOOL_IDENTIFIER",
	"STR_IDENTIFIER",
	"INT_IDENTIFIER",
	"FLOAT_IDENTIFIER",
	"MAP_IDENTIFIER",
	"STRUCT_IDENTIFIER",
	"VARIANT_IDENTIFIER",
	"IDENTIFIER",
	"CAPITALIZED_IDENTIFIER",
	"FUNC_IDENTIFIER",
	"CLASS_IDENTIFIER",
	"INCLUDE_IDENTIFIER",
	"IMPORT_IDENTIFIER",
	"AS_IDENTIFIER",
	"COMMENT",
	"ERROR",
	"COLLECT_IDENTIFIER",
	"PANIC_IDENTIFIER",
	"OR",
	"AND",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"EQ",
	"NEQ",
	"IN",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"NOT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:1997

// pos is a helper function used to track the position in the parser.
func pos(y yyLexer, dollar yySymType) {
	lp := cast(y)
	lp.row = dollar.row
	lp.col = dollar.col
	// FIXME: in some cases the before last value is most meaningful...
	//lp.row = append(lp.row, dollar.row)
	//lp.col = append(lp.col, dollar.col)
	//log.Printf("parse: %d x %d", lp.row, lp.col)
	return
}

// posLast runs pos on the last token of the current stmt/expr.
func posLast(y yyLexer, dollars []yySymType) {
	// pick the last token in the set matched by the parser
	pos(y, dollars[len(dollars)-1]) // our pos
}

// locate should be called after creating AST nodes from lexer tokens to store
// the positions of the involved tokens in the AST node.
func locate(y yyLexer, first yySymType, last yySymType, node interface{}) {
	pos(y, last)
	// Only run Locate on nodes that look like they have not received
	// locations yet otherwise the parser will come back and overwrite them
	// with invalid ending positions.
	if pn, ok := node.(interfaces.PositionableNode); !ok {
		return
	} else if !pn.IsSet() {
		//fmt.Printf("LOCATE(%v): %v, %v, %v, %v\n", node, first.row, first.col, last.endRow, last.endCol)
		pn.Locate(first.row, first.col, last.endRow, last.endCol)
	}
}

// cast is used to pull out the parser run-specific struct we store our AST in.
// this is usually called in the parser.
func cast(y yyLexer) *lexParseAST {
	x := y.(*Lexer).parseResult
	return x.(*lexParseAST)
}

// cast is used to pull out the parser run-specific struct we store our AST in.
// this is usually called in the lexer.
func (yylex *Lexer) cast() *lexParseAST {
	return yylex.parseResult.(*lexParseAST)
}

// pos is a helper function used to track the position in the lexer.
func (yylex *Lexer) pos(lval *yySymType) {
	lval.row = yylex.Line()
	lval.col = yylex.Column()

	// use: `yylex.Text()` to calculate a delta length!
	text := yylex.Text()
	lines := strings.Split(text, "\n")

	lval.endRow = lval.row + len(lines) - 1 // add delta lines
	if len(lines) > 1 {
		lval.endCol = len(lines[len(lines)-1]) // add pos of last line
	} else {
		lval.endCol = lval.col + len(text) // moved over this many chars
	}
}

// Error is the error handler which gets called on a parsing error.
func (yylex *Lexer) Error(str string) {
	lp := yylex.cast()
	if str != "" {
		// This error came from the parser. It is usually also set when
		// the lexer fails, because it ends up generating ERROR tokens,
		// which most parsers usually don't match and store in the AST.
		err := ErrParseError // TODO: add more specific types...
		if strings.HasSuffix(str, ErrParseAdditionalEquals.Error()) {
			err = ErrParseAdditionalEquals
		} else if strings.HasSuffix(str, ErrParseExpectingComma.Error()) {
			err = ErrParseExpectingComma
		} else if strings.HasPrefix(str, ErrParseSetType.Error()) {
			err = ErrParseSetType
		}
		lp.parseErr = &LexParseErr{
			Err: err,
			Str: str,
			// FIXME: get these values, by tracking pos in parser...
			// FIXME: currently, the values we get are mostly wrong!
			Row: lp.row, //lp.row[len(lp.row)-1],
			Col: lp.col, //lp.col[len(lp.col)-1],
		}
	}
}

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 157,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 81,
	-1, 158,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 82,
	-1, 159,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 83,
	-1, 160,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 84,
	-1, 161,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 85,
	-1, 162,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 86,
	-1, 167,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	53, 0,
	54, 0,
	55, 0,
	-2, 94,
}

const yyPrivate = 57344

const yyLast = 1563

var yyAct = [...]int16{
	143, 27, 230, 18, 26, 216, 192, 215, 208, 180,
	119, 179, 30, 142, 114, 137, 61, 62, 2, 201,
	174, 23, 80, 253, 56, 217, 252, 309, 59, 128,
	49, 58, 306, 100, 130, 151, 73, 279, 28, 270,
	60, 202, 104, 105, 68, 388, 345, 65, 389, 84,
	107, 101, 109, 338, 115, 120, 69, 70, 71, 72,
	74, 75, 77, 284, 129, 76, 323, 209, 131, 280,
	281, 99, 98, 94, 95, 96, 97, 92, 93, 102,
	88, 89, 90, 91, 147, 149, 150, 146, 122, 153,
	154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
	164, 165, 100, 167, 193, 148, 152, 100, 206, 301,
	191, 299, 189, 200, 181, 166, 145, 25, 63, 168,
	101, 100, 171, 107, 173, 101, 106, 194, 195, 181,
	320, 181, 172, 203, 319, 258, 83, 82, 209, 101,
	218, 302, 193, 364, 199, 197, 196, 107, 198, 88,
	89, 90, 91, 332, 318, 251, 90, 91, 286, 204,
	205, 245, 54, 243, 42, 228, 53, 224, 41, 259,
	223, 386, 31, 32, 33, 34, 361, 57, 132, 126,
	86, 127, 24, 86, 115, 241, 260, 120, 246, 247,
	59, 55, 85, 58, 248, 52, 81, 242, 237, 185,
	182, 340, 60, 329, 294, 86, 263, 236, 234, 249,
	220, 183, 178, 124, 186, 123, 9, 51, 66, 366,
	24, 285, 269, 133, 282, 283, 21, 262, 24, 287,
	257, 288, 256, 254, 266, 261, 233, 79, 181, 181,
	232, 231, 64, 229, 265, 295, 292, 219, 289, 289,
	397, 392, 303, 304, 305, 289, 298, 391, 289, 291,
	383, 289, 289, 380, 347, 379, 136, 218, 218, 311,
	316, 313, 125, 110, 108, 103, 78, 339, 336, 328,
	307, 324, 308, 135, 310, 134, 121, 325, 312, 382,
	369, 326, 358, 327, 350, 341, 330, 29, 331, 314,
	240, 54, 264, 42, 213, 53, 238, 41, 212, 335,
	211, 31, 32, 33, 34, 210, 57, 207, 22, 342,
	344, 147, 278, 277, 343, 276, 275, 337, 348, 59,
	55, 349, 58, 352, 52, 274, 355, 273, 272, 356,
	271, 60, 222, 346, 293, 235, 177, 176, 175, 267,
	368, 367, 353, 354, 221, 140, 51, 374, 373, 139,
	138, 375, 50, 377, 147, 378, 300, 376, 250, 190,
	48, 381, 47, 118, 54, 116, 42, 384, 53, 244,
	41, 187, 390, 117, 31, 32, 33, 34, 46, 57,
	393, 394, 45, 239, 184, 112, 44, 396, 43, 40,
	39, 38, 59, 55, 37, 58, 36, 52, 290, 35,
	113, 54, 73, 42, 60, 53, 111, 41, 10, 8,
	7, 31, 32, 33, 34, 6, 57, 3, 1, 51,
	0, 0, 69, 70, 71, 72, 74, 75, 77, 59,
	55, 76, 58, 0, 52, 289, 54, 73, 42, 0,
	53, 60, 41, 0, 0, 0, 31, 32, 33, 34,
	0, 57, 0, 0, 0, 0, 51, 69, 70, 71,
	72, 74, 75, 77, 59, 55, 76, 58, 54, 52,
	42, 0, 53, 0, 41, 0, 60, 0, 31, 32,
	33, 34, 0, 57, 0, 0, 0, 0, 0, 0,
	0, 51, 100, 0, 0, 0, 59, 55, 0, 58,
	28, 52, 0, 0, 363, 0, 100, 362, 60, 0,
	101, 0, 0, 0, 0, 0, 0, 0, 359, 0,
	0, 360, 0, 51, 101, 0, 0, 0, 0, 0,
	99, 98, 94, 95, 96, 97, 92, 93, 102, 88,
	89, 90, 91, 0, 99, 98, 94, 95, 96, 97,
	92, 93, 102, 88, 89, 90, 91, 268, 54, 0,
	42, 0, 53, 0, 41, 0, 0, 0, 31, 32,
	33, 34, 0, 57, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 59, 55, 0, 58,
	0, 52, 141, 54, 0, 42, 0, 53, 60, 41,
	0, 0, 0, 31, 32, 33, 34, 0, 57, 0,
	0, 0, 0, 51, 0, 0, 0, 0, 0, 0,
	0, 59, 55, 0, 58, 54, 52, 42, 100, 53,
	0, 41, 0, 60, 0, 31, 32, 33, 34, 0,
	57, 0, 81, 100, 0, 297, 101, 0, 51, 0,
	0, 0, 0, 59, 55, 395, 58, 0, 52, 0,
	0, 101, 0, 0, 0, 60, 99, 98, 94, 95,
	96, 97, 92, 93, 102, 88, 89, 90, 91, 0,
	51, 99, 98, 94, 95, 96, 97, 92, 93, 102,
	88, 89, 90, 91, 54, 0, 42, 0, 53, 0,
	41, 0, 0, 0, 31, 32, 33, 34, 0, 57,
	0, 0, 100, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 59, 55, 387, 58, 100, 52, 0, 0,
	101, 0, 0, 0, 60, 0, 0, 0, 385, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 51,
	99, 98, 94, 95, 96, 97, 92, 93, 102, 88,
	89, 90, 91, 0, 99, 98, 94, 95, 96, 97,
	92, 93, 102, 88, 89, 90, 91, 100, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 370,
	100, 0, 0, 0, 0, 101, 0, 0, 0, 0,
	0, 0, 351, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 0, 0, 99, 98, 94, 95, 96,
	97, 92, 93, 102, 88, 89, 90, 91, 99, 98,
	94, 95, 96, 97, 92, 93, 102, 88, 89, 90,
	91, 334, 0, 315, 0, 100, 0, 0, 73, 0,
	0, 0, 0, 0, 333, 0, 0, 0, 100, 24,
	0, 0, 0, 101, 0, 0, 0, 0, 69, 70,
	71, 72, 74, 75, 77, 0, 101, 76, 0, 0,
	0, 0, 0, 99, 98, 94, 95, 96, 97, 92,
	93, 102, 88, 89, 90, 91, 99, 98, 94, 95,
	96, 97, 92, 93, 102, 88, 89, 90, 91, 100,
	322, 0, 0, 73, 0, 0, 0, 0, 0, 0,
	0, 0, 100, 321, 24, 0, 0, 101, 0, 0,
	0, 0, 0, 69, 70, 71, 72, 74, 75, 77,
	101, 0, 76, 0, 0, 0, 0, 99, 98, 94,
	95, 96, 97, 92, 93, 102, 88, 89, 90, 91,
	99, 98, 94, 95, 96, 97, 92, 93, 102, 88,
	89, 90, 91, 100, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 317, 100, 0, 0, 0,
	0, 101, 0, 0, 0, 0, 0, 0, 296, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 0,
	0, 99, 98, 94, 95, 96, 97, 92, 93, 102,
	88, 89, 90, 91, 99, 98, 94, 95, 96, 97,
	92, 93, 102, 88, 89, 90, 91, 100, 227, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	100, 225, 0, 0, 0, 101, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 0, 0, 99, 98, 94, 95, 96,
	97, 92, 93, 102, 88, 89, 90, 91, 99, 98,
	94, 95, 96, 97, 92, 93, 102, 88, 89, 90,
	91, 100, 73, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 67, 170, 100, 0, 0, 0, 188, 101,
	0, 0, 69, 70, 71, 72, 74, 75, 77, 0,
	0, 76, 101, 0, 0, 0, 0, 0, 0, 99,
	98, 94, 95, 96, 97, 92, 93, 102, 88, 89,
	90, 91, 99, 98, 94, 95, 96, 97, 92, 93,
	102, 88, 89, 90, 91, 169, 0, 214, 0, 100,
	0, 0, 73, 0, 0, 0, 0, 0, 144, 0,
	0, 0, 100, 24, 0, 0, 0, 101, 0, 0,
	0, 0, 69, 70, 71, 72, 74, 75, 77, 0,
	101, 76, 0, 0, 0, 0, 0, 99, 98, 94,
	95, 96, 97, 92, 93, 102, 88, 89, 90, 91,
	99, 98, 94, 95, 96, 97, 92, 93, 102, 88,
	89, 90, 91, 87, 0, 0, 0, 100, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	100, 0, 0, 0, 0, 101, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 0, 0, 99, 98, 94, 95, 96,
	97, 92, 93, 102, 88, 89, 90, 91, 99, 98,
	94, 95, 96, 97, 92, 93, 102, 88, 89, 90,
	91, 100, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 100, 0, 0, 0, 0, 0, 0, 101,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	98, 94, 95, 96, 97, 92, 93, 102, 88, 89,
	90, 91, 94, 95, 96, 97, 92, 93, 102, 88,
	89, 90, 91, 4, 0, 372, 0, 0, 0, 0,
	11, 0, 12, 13, 4, 0, 371, 0, 0, 24,
	0, 11, 0, 12, 13, 0, 0, 0, 0, 0,
	24, 0, 0, 0, 0, 25, 28, 14, 15, 16,
	17, 0, 5, 0, 20, 19, 25, 28, 14, 15,
	16, 17, 4, 5, 365, 20, 19, 0, 0, 11,
	0, 12, 13, 4, 0, 357, 0, 0, 24, 0,
	11, 0, 12, 13, 0, 0, 0, 0, 0, 24,
	0, 0, 0, 0, 25, 28, 14, 15, 16, 17,
	0, 5, 0, 20, 19, 25, 28, 14, 15, 16,
	17, 4, 5, 255, 20, 19, 0, 0, 11, 0,
	12, 13, 4, 0, 226, 0, 0, 24, 0, 11,
	0, 12, 13, 0, 0, 0, 0, 0, 24, 0,
	0, 0, 0, 25, 28, 14, 15, 16, 17, 0,
	5, 0, 20, 19, 25, 28, 14, 15, 16, 17,
	4, 5, 0, 20, 19, 0, 0, 11, 0, 12,
	13, 0, 0, 0, 0, 0, 24, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 25, 28, 14, 15, 16, 17, 0, 5,
	0, 20, 19,
}

var yyPact = [...]int16{
	-1000, -1000, 1516, 293, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 699, 162, 162, 82, 81, -5, 202, 1103, 269,
	81, 630, 110, 109, -5, -1000, -1000, 183, -1000, -1000,
	1238, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	268, 699, 699, -1000, -1000, -1000, -1000, -1000, -1000, 119,
	267, 699, 266, 406, 369, 281, -1000, -5, -1000, -1000,
	-1000, 194, 192, 265, 174, 22, -8, 699, 159, -1000,
	-1000, -1000, -1000, 213, 280, 278, 259, -1000, 598, -1000,
	1183, 80, 1, 1, -1000, 699, -2, -1000, 699, 699,
	699, 699, 699, 699, 699, 699, 699, 699, 699, 699,
	699, 79, 699, 598, 1170, 1115, 598, -5, 598, 112,
	208, -1000, 190, -1000, -1000, 1251, -1000, 193, -1000, -1000,
	1102, 106, 95, 162, 162, 208, -1000, 208, 598, 77,
	-17, 1251, 699, 438, 438, 102, 1173, 239, -1000, -1000,
	189, -1000, -1000, 1251, -1000, -1000, -1000, 161, -1000, 158,
	1051, -1000, 1478, 98, 98, 112, 112, 93, 93, 93,
	93, 93, 93, 1313, 1302, 1038, 140, 93, 235, -1000,
	-1000, 233, -1000, 232, 228, -1000, -1000, 187, -1000, -1000,
	-1000, 438, -1000, 699, 296, -1000, 699, 157, 699, -1000,
	188, -1000, -1000, 129, -29, -32, 225, 1467, 224, 222,
	-1000, -1000, -1000, 1251, -1000, 113, -1000, 163, -1000, 438,
	219, -1000, -1000, 185, -1000, -1000, -1000, -1000, 438, -1000,
	699, 563, 33, 699, 699, 35, 209, 133, 699, -1000,
	441, -1000, -1000, 403, 162, 200, -1000, -1000, -1000, -1000,
	-1000, 987, -1000, -1000, -1000, -1000, 629, 1251, -1000, 68,
	105, 699, 699, 699, 27, -1000, 277, -15, 438, -1000,
	31, -1000, 438, 914, 849, -1000, -1000, -1000, -1000, 974,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	128, 108, 923, 910, 30, 276, 699, 1251, 1251, -1000,
	-1000, 274, -1000, -1000, -1000, 182, 292, 699, -1000, -1000,
	-1000, -1000, 127, 1251, 859, 846, -1000, 273, -1000, 17,
	271, -1000, -1000, -1000, -1000, -1000, 180, 291, 699, 473,
	10, -1000, 35, -1000, -1000, 1251, 258, 441, -1000, 290,
	-1000, 791, 699, -1000, -1000, 441, -1000, 1429, -1000, -1000,
	288, -1000, 507, 155, 493, 117, 1418, 207, 1251, 441,
	-1000, 286, 778, 1380, 1369, 1251, 441, -1000, -1000, -1000,
	699, -1000, 473, -1000, 699, -1000, 260, 257, 1251, -1000,
	285, -1000, -1000, 254, 1251, 727, 150, 713, 24, -1000,
	-1000, 251, -1000, -1000, 245, -1000, -1000, -1000, -1000, 699,
	441, -1000, -1000, 644, 1251, -1000, 244, -1000,
}

var yyPgo = [...]int16{
	0, 428, 18, 427, 425, 420, 419, 216, 418, 0,
	3, 20, 2, 25, 226, 30, 15, 409, 406, 404,
	401, 400, 399, 398, 396, 395, 14, 394, 393, 392,
	388, 383, 10, 381, 379, 372, 370, 369, 6, 368,
	366, 362, 360, 359, 355, 13, 354, 349, 348, 347,
	346, 11, 9, 345, 344, 342, 340, 338, 337, 335,
	326, 325, 323, 322, 4, 318, 21, 1, 317, 315,
	8, 310, 308, 304, 7, 5, 302, 299, 24,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 9, 9, 9, 9,
	9, 9, 9, 9, 9, 9, 9, 9, 17, 17,
	23, 23, 25, 25, 26, 24, 27, 27, 27, 28,
	18, 18, 29, 29, 31, 31, 32, 30, 33, 33,
	33, 34, 19, 19, 35, 35, 37, 37, 38, 36,
	39, 39, 39, 40, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 16, 16, 16, 42, 44,
	44, 45, 43, 46, 46, 46, 47, 21, 22, 22,
	11, 11, 11, 48, 50, 50, 51, 49, 53, 53,
	53, 54, 52, 52, 4, 4, 5, 6, 7, 55,
	55, 55, 55, 55, 55, 55, 55, 55, 55, 56,
	57, 58, 59, 60, 61, 62, 63, 8, 8, 65,
	65, 64, 66, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 68, 68, 70, 69, 69, 69, 71,
	73, 73, 74, 72, 76, 76, 76, 77, 75, 75,
	78, 78, 78, 10, 14, 14, 15, 15, 41, 67,
	67, 12, 12,
}

var yyR2 = [...]int8{
	0, 1, 0, 3, 2, 1, 1, 1, 1, 1,
	1, 5, 9, 9, 9, 10, 11, 5, 8, 2,
	5, 4, 7, 2, 4, 4, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 13, 3, 1, 1,
	2, 3, 3, 1, 1, 4, 0, 2, 2, 3,
	1, 1, 2, 3, 3, 1, 3, 4, 0, 2,
	2, 5, 1, 1, 3, 4, 3, 1, 3, 5,
	0, 2, 2, 5, 4, 4, 4, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	4, 6, 3, 5, 3, 0, 1, 1, 1, 3,
	1, 1, 2, 0, 2, 2, 3, 1, 9, 10,
	0, 1, 1, 1, 3, 1, 1, 2, 0, 2,
	2, 3, 1, 2, 3, 4, 4, 2, 5, 0,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 4,
	6, 4, 6, 6, 8, 4, 6, 1, 3, 1,
	3, 4, 6, 1, 1, 1, 1, 3, 6, 3,
	4, 5, 1, 3, 1, 2, 0, 1, 1, 1,
	3, 1, 1, 2, 0, 2, 2, 3, 1, 2,
	1, 1, 1, 2, 1, 3, 1, 3, 2, 1,
	3, 0, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 4, 43, -4, -5, -6, -7,
	-8, 11, 13, 14, 38, 39, 40, 41, -10, 46,
	45, -14, -65, -66, 20, 36, -64, -67, 37, 4,
	-9, 15, 16, 17, 18, -17, -18, -19, -20, -21,
	-22, 11, 7, -23, -24, -29, -30, -35, -36, -15,
	-41, 60, 38, 9, 5, 34, -78, 20, 36, 33,
	45, -10, -10, 36, -14, -15, 16, 19, -13, 29,
	30, 31, 32, 9, 33, 34, 38, 35, 7, -7,
	-9, 22, 27, 27, -78, 9, 22, 5, 56, 57,
	58, 59, 53, 54, 49, 50, 51, 52, 48, 47,
	9, 27, 55, 7, -9, -9, 7, 28, 7, -9,
	7, 10, -25, 4, -26, -9, 6, -31, 4, -32,
	-9, 5, -15, 21, 21, 7, 5, 7, 7, 42,
	42, -9, 19, 10, 5, 5, 7, -16, -42, -43,
	-44, 4, -45, -9, 5, 36, -64, -67, -66, -67,
	-9, 37, -2, -9, -9, -9, -9, -9, -9, -9,
	-9, -9, -9, -9, -9, -9, 36, -9, -16, 5,
	8, -16, -78, -16, -11, -48, -49, -50, 4, -51,
	-52, -10, 10, 21, -27, 6, 21, -33, 26, 6,
	-37, 4, -38, 36, -10, -10, -11, -2, -11, -16,
	36, 36, 58, -9, -13, -13, 6, -68, -70, 36,
	-69, -71, -72, -73, 4, -74, -75, -13, -10, 8,
	21, -46, -55, 9, 9, 10, 6, 10, 25, 8,
	-12, 8, 8, 8, 21, -53, -13, -26, 10, -28,
	4, -9, -32, 6, -34, 4, -9, -9, 6, 21,
	-39, 26, 55, 55, 8, 6, 8, 8, 22, 6,
	23, -13, 8, 21, -76, -13, -45, -47, 4, -9,
	6, -56, -57, -58, -59, -60, -61, -62, -63, 4,
	36, 37, -9, -9, 28, 12, 25, -9, -9, 4,
	5, -13, -51, -54, 4, -52, 21, 26, -38, 6,
	-40, 4, 36, -9, -9, -9, 5, -13, 5, 42,
	-13, -70, -13, -74, -77, 4, -75, 21, 26, 26,
	22, 10, 10, 36, 5, -9, -12, -12, 5, 21,
	4, -9, 26, 5, 5, -12, 5, -2, 36, 6,
	21, 4, -9, -64, -9, 36, -2, 6, -9, -12,
	4, 21, -9, -2, -2, -9, -12, 6, 4, 21,
	24, 21, 24, 21, 26, 6, 12, -12, -9, 4,
	21, 6, 6, -12, -9, -9, -64, -9, -9, 5,
	6, -12, 4, 6, -12, 21, 21, 21, 21, 24,
	-12, 6, 6, -9, -9, 21, -12, 6,
}

var yyDef = [...]int16{
	2, -2, 1, 0, 4, 5, 6, 7, 8, 9,
	10, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 147, 0, 0, 184, 149, 0, 189, 3,
	0, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 0, 0, 38, 39, 50, 51, 62, 63, 0,
	107, 0, 0, 0, 0, 0, 186, 0, 180, 181,
	182, 0, 0, 0, 0, 19, 23, 0, 0, 153,
	154, 155, 156, 0, 0, 0, 0, 162, 95, 127,
	0, 0, 0, 0, 183, 0, 0, 2, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 95, 0, 0, 95, 0, 95, 89,
	110, 40, 0, 46, 43, 44, 52, 0, 58, 55,
	0, 0, 188, 0, 0, 110, 2, 110, 95, 0,
	0, 124, 0, 0, 0, 0, 166, 0, 96, 97,
	98, 103, 100, 101, 129, 185, 150, 0, 148, 0,
	0, 190, 0, 77, 78, 79, 80, -2, -2, -2,
	-2, -2, -2, 87, 88, 0, 92, -2, 0, 191,
	37, 0, 187, 0, 0, 111, 112, 113, 118, 115,
	116, 122, 41, 0, 0, 53, 0, 0, 0, 64,
	0, 70, 67, 0, 0, 0, 0, 0, 0, 0,
	21, 24, 25, 125, 157, 0, 159, 0, 164, 0,
	0, 167, 168, 169, 174, 171, 172, 178, 0, 126,
	0, 102, 0, 0, 0, 151, 11, 90, 0, 76,
	0, 74, 75, 0, 0, 117, 123, 42, 45, 47,
	48, 0, 54, 57, 59, 60, 0, 56, 65, 0,
	0, 0, 0, 0, 0, 17, 0, 20, 0, 160,
	0, 165, 0, 0, 173, 179, 99, 104, 105, 0,
	128, 130, 131, 132, 133, 134, 135, 136, 137, 138,
	0, 0, 0, 0, 0, 0, 0, 93, 191, 192,
	191, 0, 114, 119, 120, 0, 0, 0, 66, 69,
	71, 72, 0, 68, 0, 0, 191, 0, 2, 0,
	0, 163, 161, 170, 175, 176, 0, 0, 0, 0,
	0, 151, 0, 152, 2, 91, 0, 0, 191, 0,
	49, 0, 0, 2, 2, 0, 191, 0, 22, 158,
	0, 106, 0, 0, 0, 0, 0, 0, 191, 0,
	121, 0, 0, 0, 0, 191, 0, 18, 177, 139,
	0, 141, 0, 145, 0, 12, 0, 0, 191, 61,
	0, 13, 14, 0, 191, 0, 0, 0, 0, 191,
	108, 0, 73, 15, 0, 140, 142, 146, 143, 0,
	0, 109, 16, 0, 191, 144, 0, 36,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{
	{342, 6, errstrParseExpectingComma},
	{342, 6, errstrParseExpectingComma},
	{342, 6, errstrParseExpectingComma},
	{342, 6, errstrParseExpectingComma},
	{342, 6, errstrParseExpectingComma},
	{342, 4, errstrParseExpectingComma},
	{342, 4, errstrParseExpectingComma},
	{342, 4, errstrParseExpectingComma},
	{342, 4, errstrParseExpectingComma},
	{342, 4, errstrParseExpectingComma},
	{18, 53, errstrParseAdditionalEquals},
	{18, 53, errstrParseAdditionalEquals},
	{18, 53, errstrParseAdditionalEquals},
	{18, 53, errstrParseAdditionalEquals},
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:153
		{
			posLast(yylex, yyDollar) // our pos
			// store the AST in the struct that we previously passed in
			lp := cast(yylex)
			lp.ast = yyDollar[1].stmt
			// this is equivalent to:
			//lp := yylex.(*Lexer).parseResult
			//lp.(*lexParseAST).ast = $1.stmt
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:184
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.stmt = &ast.StmtProg{
				Body: []interfaces.Stmt{},
			}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:191
		{
			posLast(yylex, yyDollar) // our pos
			// TODO: should we just skip comments for now?
			//if _, ok := $2.stmt.(*ast.StmtComment); !ok {
			//}
			if stmt, ok := yyDollar[1].stmt.(*ast.StmtProg); ok {
				stmts := stmt.Body
				stmts = append(stmts, yyDollar[2].stmt)
				yyVAL.stmt = &ast.StmtProg{
					Body: stmts,
				}
				locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:207
		{
			// newline!
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:214
		{
			yyVAL.stmt = &ast.StmtComment{
				Value: yyDollar[1].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:221
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:226
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:231
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:236
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:241
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:246
		{
			yyVAL.stmt = &ast.StmtIf{
				Condition:  yyDollar[2].expr,
				ThenBranch: yyDollar[4].stmt,
				//ElseBranch: nil,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 12:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:255
		{
			yyVAL.stmt = &ast.StmtIf{
				Condition:  yyDollar[2].expr,
				ThenBranch: yyDollar[4].stmt,
				ElseBranch: yyDollar[8].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 13:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:266
		{
			yyVAL.stmt = &ast.StmtFor{
				Index: yyDollar[2].str,  // no $ prefix
				Value: yyDollar[4].str,  // no $ prefix
				Expr:  yyDollar[6].expr, // XXX: name this List ?
				Body:  yyDollar[8].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 14:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:278
		{
			yyVAL.stmt = &ast.StmtForKV{
				Key:  yyDollar[2].str,  // no $ prefix
				Val:  yyDollar[4].str,  // no $ prefix
				Expr: yyDollar[6].expr, // XXX: name this Map ?
				Body: yyDollar[8].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 15:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser/parser.y:292
		{
			yyVAL.stmt = &ast.StmtFunc{
				Name: yyDollar[2].str,
				Func: &ast.ExprFunc{
					Title:  yyDollar[2].str,
					Args:   yyDollar[4].args,
					Return: nil,
					Body:   yyDollar[8].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 16:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser/parser.y:306
		{
			fn := &ast.ExprFunc{
				Title:  yyDollar[2].str,
				Args:   yyDollar[4].args,
				Return: yyDollar[6].typ, // return type is known
				Body:   yyDollar[9].expr,
			}
			isFullyTyped := yyDollar[6].typ != nil // true if set
			m := make(map[string]*types.Type)
			ord := []string{}
			for _, a := range yyDollar[4].args {
				if a.Type == nil {
					// at least one is unknown, can't run SetType...
					isFullyTyped = false
					break
				}
				m[a.Name] = a.Type
				ord = append(ord, a.Name)
			}
			var typ *types.Type
			if isFullyTyped {
				typ = &types.Type{
					Kind: types.KindFunc,
					Map:  m,
					Ord:  ord,
					Out:  yyDollar[6].typ,
				}
				// XXX: We might still need to do this for now...
				if err := fn.SetType(typ); err != nil {
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
				}
			}
			yyVAL.stmt = &ast.StmtFunc{
				Name: yyDollar[2].str,
				Func: fn,
				Type: typ, // sam says add the type here instead...
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:348
		{
			yyVAL.stmt = &ast.StmtClass{
				Name: yyDollar[2].str,
				Args: nil,
				Body: yyDollar[4].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 18:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:359
		{
			yyVAL.stmt = &ast.StmtClass{
				Name: yyDollar[2].str,
				Args: yyDollar[4].args,
				Body: yyDollar[7].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:369
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name: yyDollar[2].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:377
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name: yyDollar[2].str,
				Args: yyDollar[4].exprs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:387
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name:  yyDollar[2].str,
				Alias: yyDollar[4].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 22:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:397
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name:  yyDollar[2].str,
				Args:  yyDollar[4].exprs,
				Alias: yyDollar[7].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:407
		{
			yyVAL.stmt = &ast.StmtImport{
				Name: yyDollar[2].str,
				//Alias: "",
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:416
		{
			yyVAL.stmt = &ast.StmtImport{
				Name:  yyDollar[2].str,
				Alias: yyDollar[4].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:425
		{
			yyVAL.stmt = &ast.StmtImport{
				Name:  yyDollar[2].str,
				Alias: yyDollar[4].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:443
		{
			yyVAL.expr = &ast.ExprBool{
				V: yyDollar[1].bool,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:450
		{
			yyVAL.expr = &ast.ExprStr{
				V: yyDollar[1].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:457
		{
			yyVAL.expr = &ast.ExprInt{
				V: yyDollar[1].int,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:464
		{
			yyVAL.expr = &ast.ExprFloat{
				V: yyDollar[1].float,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:471
		{
			// TODO: list could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:477
		{
			// TODO: map could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:483
		{
			// TODO: struct could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:489
		{
			// TODO: call could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:495
		{
			// TODO: var could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:501
		{
			// TODO: var could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 36:
		yyDollar = yyS[yypt-13 : yypt+1]
//line parser/parser.y:507
		{
			yyVAL.expr = &ast.ExprIf{
				Condition:  yyDollar[2].expr,
				ThenBranch: yyDollar[5].expr,
				ElseBranch: yyDollar[11].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:517
		{
			yyVAL.expr = yyDollar[2].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:524
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:529
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:536
		{
			yyVAL.expr = &ast.ExprList{
				Elements: []interfaces.Expr{},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:544
		{
			yyVAL.expr = &ast.ExprList{
				Elements: yyDollar[2].exprs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:553
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:558
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:565
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:577
		{
			yyVAL.expr = &ast.ExprList{
				Elements: yyDollar[3].exprs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 46:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:586
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = []interfaces.Expr{}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:591
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[2].expr)
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:597
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:604
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:611
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:616
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:623
		{
			yyVAL.expr = &ast.ExprMap{
				KVs: []*ast.ExprMapKV{},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:631
		{
			yyVAL.expr = &ast.ExprMap{
				KVs: yyDollar[2].mapKVs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:640
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = append(yyDollar[1].mapKVs, yyDollar[3].mapKV)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:645
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = append(yyVAL.mapKVs, yyDollar[1].mapKV)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:652
		{
			yyVAL.mapKV = &ast.ExprMapKV{
				Key: yyDollar[1].expr,
				Val: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.mapKV)
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:666
		{
			yyVAL.expr = &ast.ExprMap{
				KVs: yyDollar[3].mapKVs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 58:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:675
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = []*ast.ExprMapKV{}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:680
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = append(yyDollar[1].mapKVs, yyDollar[2].mapKV)
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:686
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = yyDollar[1].mapKVs
		}
	case 61:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:693
		{
			yyVAL.mapKV = &ast.ExprMapKV{
				Key: yyDollar[1].expr,
				Val: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.mapKV)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:703
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:708
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:715
		{
			yyVAL.expr = &ast.ExprStruct{
				Fields: []*ast.ExprStructField{},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:723
		{
			yyVAL.expr = &ast.ExprStruct{
				Fields: yyDollar[3].structFields,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:732
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = append(yyDollar[1].structFields, yyDollar[3].structField)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:737
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = append(yyVAL.structFields, yyDollar[1].structField)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:744
		{
			yyVAL.structField = &ast.ExprStructField{
				Name:  yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.structField)
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:759
		{
			yyVAL.expr = &ast.ExprStruct{
				Fields: yyDollar[4].structFields,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:768
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = []*ast.ExprStructField{}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:773
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = append(yyDollar[1].structFields, yyDollar[2].structField)
		}
	case 72:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:779
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = yyDollar[1].structFields
		}
	case 73:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:786
		{
			yyVAL.structField = &ast.ExprStructField{
				Name:  yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.structField)
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:798
		{
			yyVAL.expr = &ast.ExprCall{
				Name: yyDollar[1].str,
				Args: yyDollar[3].exprs,
				//Var: false, // default
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:809
		{
			yyVAL.expr = &ast.ExprCall{
				Name: yyDollar[1].str,
				Args: yyDollar[3].exprs,
				// Instead of `Var: true`, we could have added a `$`
				// prefix to the Name, but I felt this was more elegant.
				Var: true, // lambda
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:821
		{
			yyVAL.expr = &ast.ExprCall{
				Name: "", // anonymous!
				Args: yyDollar[3].exprs,
				Anon: yyDollar[1].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:830
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str, // for PLUS this is a `+` character
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:844
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:858
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:872
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:886
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:900
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:914
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:928
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:942
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:956
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:970
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:984
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:998
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[1].str,
					},
					yyDollar[2].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 90:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1014
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.LookupFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the list or map
					yyDollar[3].expr, // the index or key is an expr
					//$6.expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 91:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1029
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.LookupDefaultFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the list or map
					yyDollar[3].expr, // the index or key is an expr
					yyDollar[6].expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1044
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.StructLookupFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the struct
					&ast.ExprStr{
						V: yyDollar[3].str, // the field is always an str
					},
					//$5.expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 93:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:1061
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.StructLookupOptionalFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the struct
					&ast.ExprStr{
						V: yyDollar[3].str, // the field is always an str
					},
					yyDollar[5].expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1075
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.ContainsFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 95:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1090
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = []interfaces.Expr{}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1095
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1100
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1108
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1116
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1121
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1128
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1138
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = yyDollar[2].exprs
		}
	case 103:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1145
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = []interfaces.Expr{}
		}
	case 104:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1150
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[2].expr)
		}
	case 105:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1156
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1163
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.expr = yyDollar[1].expr
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1170
		{
			yyVAL.expr = &ast.ExprVar{
				Name: yyDollar[1].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 108:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:1183
		{
			yyVAL.expr = &ast.ExprFunc{
				Args: yyDollar[3].args,
				//Return: nil,
				Body: yyDollar[7].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 109:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser/parser.y:1193
		{
			yyVAL.expr = &ast.ExprFunc{
				Args:   yyDollar[3].args,
				Return: yyDollar[5].typ, // return type is known
				Body:   yyDollar[8].expr,
			}
			isFullyTyped := yyDollar[5].typ != nil // true if set
			m := make(map[string]*types.Type)
			ord := []string{}
			for _, a := range yyDollar[3].args {
				if a.Type == nil {
					// at least one is unknown, can't run SetType...
					isFullyTyped = false
					break
				}
				m[a.Name] = a.Type
				ord = append(ord, a.Name)
			}
			if isFullyTyped {
				typ := &types.Type{
					Kind: types.KindFunc,
					Map:  m,
					Ord:  ord,
					Out:  yyDollar[5].typ,
				}
				if err := yyVAL.expr.SetType(typ); err != nil {
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
				}
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 110:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1230
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1235
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1240
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1248
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1255
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].arg)
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1260
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append([]*interfaces.Arg{}, yyDollar[1].arg)
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1267
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.arg = yyDollar[1].arg
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1277
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[2].args
		}
	case 118:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1284
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1289
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[2].arg)
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1295
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1302
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.arg = yyDollar[1].arg
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1310
		{
			yyVAL.arg = &interfaces.Arg{
				Name: yyDollar[1].str,
			}
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1317
		{
			yyVAL.arg = &interfaces.Arg{
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1327
		{
			yyVAL.stmt = &ast.StmtBind{
				Ident: yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 125:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1337
		{
			var expr interfaces.Expr = yyDollar[4].expr
			// XXX: We still need to do this for now it seems...
			if err := expr.SetType(yyDollar[2].typ); err != nil {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
			}
			yyVAL.stmt = &ast.StmtBind{
				Ident: yyDollar[1].str,
				Value: expr,
				Type:  yyDollar[2].typ, // sam says add the type here instead...
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 126:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1359
		{
			funcName := yyDollar[1].str // funcs.PanicFuncName
			if len(yyDollar[3].exprs) == 2 {
				funcName = funcs.PanicDebugFuncName
			}
			call := &ast.ExprCall{
				Name: funcName, // the function name
				Args: yyDollar[3].exprs,
				//Var: false, // default
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], call)
			name := &ast.ExprStr{
				V: yyDollar[1].str, // any constant, non-empty name
			}
			res := &ast.StmtRes{
				Kind:     interfaces.PanicResKind,
				Name:     name,
				Contents: []ast.StmtResContents{},
			}
			yyVAL.stmt = &ast.StmtIf{
				Condition:  call,
				ThenBranch: res,
				//ElseBranch: nil,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1391
		{
			// A "collect" stmt is exactly a regular "res" statement, except
			// it has the boolean "Collect" field set to true, and it also
			// has a special "resource body" entry which accepts the special
			// collected data from the function graph.
			yyVAL.stmt = yyDollar[2].stmt // it's us now
			kind := yyDollar[2].stmt.(*ast.StmtRes).Kind
			res := yyVAL.stmt.(*ast.StmtRes)
			res.Collect = true
			// We are secretly adding a special field to the res contents,
			// which receives all of the exported data so that we have it
			// arrive in our function graph in the standard way. We'd need
			// to have this data to be able to build the resources we want!
			call := &ast.ExprCall{
				// function name to lookup special values from that kind
				Name: funcs.CollectFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // magic operator first
						V: kind, // tell it what we're reading
					},
					// names to collect
					// XXX: Can we copy the same AST nodes to here?
					// XXX: Do I need to run .Copy() on them ?
					// str, []str, or []struct{name str; host str}
					res.Name, // expr (hopefully one of those types)
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], call)
			collect := &ast.StmtResCollect{ // special field
				Kind:  kind, // might as well tell it directly
				Value: call,
			}
			res.Contents = append(res.Contents, collect)
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 128:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:1446
		{
			yyVAL.stmt = &ast.StmtRes{
				Kind:     yyDollar[1].str,
				Name:     yyDollar[2].expr,
				Contents: yyDollar[4].resContents,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 129:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1457
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = []ast.StmtResContents{}
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1462
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resField)
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1467
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resField)
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1472
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resEdge)
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1477
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resEdge)
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1482
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 135:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1487
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1492
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1497
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1503
		{
			// newline!
			yyVAL.resContents = yyDollar[1].resContents
		}
	case 139:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1510
		{
			yyVAL.resField = &ast.StmtResField{
				Field: yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resField)
		}
	case 140:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1521
		{
			yyVAL.resField = &ast.StmtResField{
				Field:     yyDollar[1].str,
				Value:     yyDollar[5].expr,
				Condition: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resField)
		}
	case 141:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1533
		{
			yyVAL.resEdge = &ast.StmtResEdge{
				Property: yyDollar[1].str,
				EdgeHalf: yyDollar[3].edgeHalf,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resEdge)
		}
	case 142:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1544
		{
			yyVAL.resEdge = &ast.StmtResEdge{
				Property:  yyDollar[1].str,
				EdgeHalf:  yyDollar[5].edgeHalf,
				Condition: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resEdge)
		}
	case 143:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1556
		{
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property: yyDollar[3].str,
				MetaExpr: yyDollar[5].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 144:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:1571
		{
			posLast(yylex, yyDollar) // our pos
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property:  yyDollar[3].str,
				MetaExpr:  yyDollar[7].expr,
				Condition: yyDollar[5].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 145:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1588
		{
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property: yyDollar[1].str,
				MetaExpr: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 146:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1603
		{
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property:  yyDollar[1].str,
				MetaExpr:  yyDollar[5].expr,
				Condition: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1621
		{
			yyVAL.stmt = &ast.StmtEdge{
				EdgeHalfList: yyDollar[1].edgeHalfList,
				//Notify: false, // unused here
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1630
		{
			yyVAL.stmt = &ast.StmtEdge{
				EdgeHalfList: []*ast.StmtEdgeHalf{
					yyDollar[1].edgeHalf,
					yyDollar[3].edgeHalf,
				},
				//Notify: false, // unused here, it is implied (i think)
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1643
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.edgeHalfList = []*ast.StmtEdgeHalf{yyDollar[1].edgeHalf}
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1648
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.edgeHalfList = append(yyDollar[1].edgeHalfList, yyDollar[3].edgeHalf)
		}
	case 151:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1656
		{
			yyVAL.edgeHalf = &ast.StmtEdgeHalf{
				Kind: yyDollar[1].str,
				Name: yyDollar[3].expr,
				//SendRecv: "", // unused
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.edgeHalf)
		}
	case 152:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1668
		{
			yyVAL.edgeHalf = &ast.StmtEdgeHalf{
				Kind:     yyDollar[1].str,
				Name:     yyDollar[3].expr,
				SendRecv: yyDollar[6].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.edgeHalf)
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1679
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "bool"
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1684
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "str"
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1689
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "int"
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1694
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "float"
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1700
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.typ = types.NewType("[]" + yyDollar[3].typ.String())
		}
	case 158:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1706
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.typ = types.NewType(fmt.Sprintf("map{%s: %s}", yyDollar[3].typ.String(), yyDollar[5].typ.String()))
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1712
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.typ = types.NewType(fmt.Sprintf("%s{}", yyDollar[1].str))
		}
	case 160:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1718
		{
			posLast(yylex, yyDollar) // our pos

			names := make(map[string]struct{})
			strs := []string{}
			for _, arg := range yyDollar[3].args {
				s := fmt.Sprintf("%s %s", arg.Name, arg.Type.String())
				if _, exists := names[arg.Name]; exists {
					// duplicate field name used
					err := fmt.Errorf("duplicate struct field of `%s`", s)
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
					break // we must skip, because code continues!
				}
				names[arg.Name] = struct{}{}
				strs = append(strs, s)
			}

			yyVAL.typ = types.NewType(fmt.Sprintf("%s{%s}", yyDollar[1].str, strings.Join(strs, "; ")))
		}
	case 161:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:1741
		{
			posLast(yylex, yyDollar) // our pos

			m := make(map[string]*types.Type)
			ord := []string{}
			for i, a := range yyDollar[3].args {
				if a.Type == nil {
					// at least one is unknown, can't run SetType...
					// this means there is a programming error here!
					err := fmt.Errorf("type is unspecified for arg #%d", i)
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
					break // safety
				}
				name := a.Name
				if name == "" {
					name = util.NumToAlpha(i) // if unspecified...
				}
				if util.StrInList(name, ord) {
					// duplicate arg name used
					err := fmt.Errorf("duplicate arg name of `%s`", name)
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
					break // safety
				}
				m[name] = a.Type
				ord = append(ord, name)
			}

			yyVAL.typ = &types.Type{
				Kind: types.KindFunc,
				Map:  m,
				Ord:  ord,
				Out:  yyDollar[5].typ,
			}
		}
	case 162:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1778
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "variant"
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1785
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].arg)
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1790
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append([]*interfaces.Arg{}, yyDollar[1].arg)
		}
	case 165:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1797
		{
			posLast(yylex, yyDollar)     // our pos
			yyVAL.arg = &interfaces.Arg{ // reuse the Arg struct
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1811
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1816
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1821
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1829
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1836
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].arg)
		}
	case 171:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1841
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append([]*interfaces.Arg{}, yyDollar[1].arg)
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1848
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.arg = yyDollar[1].arg
		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1857
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[2].args
		}
	case 174:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1864
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 175:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1869
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[2].arg)
		}
	case 176:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1875
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = yyDollar[1].args
		}
	case 177:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1882
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.arg = yyDollar[1].arg
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1890
		{
			yyVAL.arg = &interfaces.Arg{
				Type: yyDollar[1].typ,
			}
		}
	case 179:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1898
		{
			yyVAL.arg = &interfaces.Arg{
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1907
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1913
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1919
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1927
		{
			posLast(yylex, yyDollar)          // our pos
			yyVAL.str = yyDollar[2].str       // don't include the leading $
			yyVAL.endRow = yyDollar[2].endRow // propagate end position from identifier
			yyVAL.endCol = yyDollar[2].endCol
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1937
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1943
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str + yyDollar[2].str + yyDollar[3].str
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1950
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 187:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1955
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str + interfaces.ModuleSep + yyDollar[3].str
		}
	case 188:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1964
		{
			posLast(yylex, yyDollar)          // our pos
			yyVAL.str = yyDollar[2].str       // don't include the leading $
			yyVAL.endRow = yyDollar[2].endRow // propagate end position from identifier
			yyVAL.endCol = yyDollar[2].endCol
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1973
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 190:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1978
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str + yyDollar[2].str + yyDollar[3].str
		}
	case 191:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1989
		{
			// no newline
		}
	case 192:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1993
		{
			// newline!
		}
	}
	goto yystack /* stack new state and value */
}
