// Mgmt
// Copyright (C) James Shubin and the project contributors
// Written by James Shubin <james@shubin.ca> and the project contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Additional permission under GNU GPL version 3 section 7
//
// If you modify this program, or any covered work, by linking or combining it
// with embedded mcl code and modules (and that the embedded mcl code and
// modules which link with this program, contain a copy of their source code in
// the authoritative form) containing parts covered by the terms of any other
// license, the licensors of this program grant you additional permission to
// convey the resulting work. Furthermore, the licensors of this program grant
// the original author, James Shubin, additional permission to update this
// additional permission if he deems it necessary to achieve the goals of this
// additional permission.

// Code generated by goyacc -v parser/y.output -o parser/y.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:31
package parser

import __yyfmt__ "fmt"

//line parser/parser.y:31

import (
	"fmt"
	"strings"

	"github.com/purpleidea/mgmt/lang/ast"
	"github.com/purpleidea/mgmt/lang/funcs"
	"github.com/purpleidea/mgmt/lang/funcs/operators"
	"github.com/purpleidea/mgmt/lang/interfaces"
	"github.com/purpleidea/mgmt/lang/types"
	"github.com/purpleidea/mgmt/util"
)

const (
	errstrParseAdditionalEquals = "additional equals in bind statement"
	errstrParseExpectingComma   = "expecting trailing comma"
)

func init() {
	yyErrorVerbose = true // set the global that enables showing full errors
}

//line parser/parser.y:55
type yySymType struct {
	yys int
	row int
	col int

	//err error // TODO: if we ever match ERROR in the parser

	bool  bool
	str   string
	int   int64 // this is the .int as seen in lexer.nex
	float float64

	typ *types.Type

	stmts []interfaces.Stmt
	stmt  interfaces.Stmt

	exprs []interfaces.Expr
	expr  interfaces.Expr

	mapKVs []*ast.ExprMapKV
	mapKV  *ast.ExprMapKV

	structFields []*ast.ExprStructField
	structField  *ast.ExprStructField

	args []*interfaces.Arg
	arg  *interfaces.Arg

	resContents []ast.StmtResContents // interface
	resField    *ast.StmtResField
	resEdge     *ast.StmtResEdge
	resMeta     *ast.StmtResMeta

	edgeHalfList []*ast.StmtEdgeHalf
	edgeHalf     *ast.StmtEdgeHalf
}

const OPEN_CURLY = 57346
const CLOSE_CURLY = 57347
const OPEN_PAREN = 57348
const CLOSE_PAREN = 57349
const OPEN_BRACK = 57350
const CLOSE_BRACK = 57351
const IF = 57352
const ELSE = 57353
const FOR = 57354
const FORKV = 57355
const BOOL = 57356
const STRING = 57357
const INTEGER = 57358
const FLOAT = 57359
const EQUALS = 57360
const DOLLAR = 57361
const COMMA = 57362
const COLON = 57363
const SEMICOLON = 57364
const ELVIS = 57365
const DEFAULT = 57366
const ROCKET = 57367
const ARROW = 57368
const DOT = 57369
const BOOL_IDENTIFIER = 57370
const STR_IDENTIFIER = 57371
const INT_IDENTIFIER = 57372
const FLOAT_IDENTIFIER = 57373
const MAP_IDENTIFIER = 57374
const STRUCT_IDENTIFIER = 57375
const VARIANT_IDENTIFIER = 57376
const IDENTIFIER = 57377
const CAPITALIZED_IDENTIFIER = 57378
const FUNC_IDENTIFIER = 57379
const CLASS_IDENTIFIER = 57380
const INCLUDE_IDENTIFIER = 57381
const IMPORT_IDENTIFIER = 57382
const AS_IDENTIFIER = 57383
const COMMENT = 57384
const ERROR = 57385
const PANIC_IDENTIFIER = 57386
const AND = 57387
const OR = 57388
const LT = 57389
const GT = 57390
const LTE = 57391
const GTE = 57392
const EQ = 57393
const NEQ = 57394
const PLUS = 57395
const MINUS = 57396
const MULTIPLY = 57397
const DIVIDE = 57398
const NOT = 57399
const IN = 57400

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"OPEN_CURLY",
	"CLOSE_CURLY",
	"OPEN_PAREN",
	"CLOSE_PAREN",
	"OPEN_BRACK",
	"CLOSE_BRACK",
	"IF",
	"ELSE",
	"FOR",
	"FORKV",
	"BOOL",
	"STRING",
	"INTEGER",
	"FLOAT",
	"EQUALS",
	"DOLLAR",
	"COMMA",
	"COLON",
	"SEMICOLON",
	"ELVIS",
	"DEFAULT",
	"ROCKET",
	"ARROW",
	"DOT",
	"BOOL_IDENTIFIER",
	"STR_IDENTIFIER",
	"INT_IDENTIFIER",
	"FLOAT_IDENTIFIER",
	"MAP_IDENTIFIER",
	"STRUCT_IDENTIFIER",
	"VARIANT_IDENTIFIER",
	"IDENTIFIER",
	"CAPITALIZED_IDENTIFIER",
	"FUNC_IDENTIFIER",
	"CLASS_IDENTIFIER",
	"INCLUDE_IDENTIFIER",
	"IMPORT_IDENTIFIER",
	"AS_IDENTIFIER",
	"COMMENT",
	"ERROR",
	"PANIC_IDENTIFIER",
	"AND",
	"OR",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"EQ",
	"NEQ",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"NOT",
	"IN",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:1504

// pos is a helper function used to track the position in the parser.
func pos(y yyLexer, dollar yySymType) {
	lp := cast(y)
	lp.row = dollar.row
	lp.col = dollar.col
	// FIXME: in some cases the before last value is most meaningful...
	//lp.row = append(lp.row, dollar.row)
	//lp.col = append(lp.col, dollar.col)
	//log.Printf("parse: %d x %d", lp.row, lp.col)
	return
}

// cast is used to pull out the parser run-specific struct we store our AST in.
// this is usually called in the parser.
func cast(y yyLexer) *lexParseAST {
	x := y.(*Lexer).parseResult
	return x.(*lexParseAST)
}

// locate should be called after creating AST nodes from lexer tokens to store
// the positions of the involved tokens in the AST node.
func locate(y yyLexer, first yySymType, last yySymType, node interface{}) {
	pos(y, last)
	// Only run Locate on nodes that look like they have not received
	// locations yet otherwise the parser will come back and overwrite them
	// with invalid ending positions.
	if pn, ok := node.(interfaces.PositionableNode); !ok {
		return
	} else if !pn.IsSet() {
		pn.Locate(first.row, first.col, last.row, last.col)
	}
}

// posLast runs pos on the last token of the current stmt/expr.
func posLast(y yyLexer, dollars []yySymType) {
	// pick the last token in the set matched by the parser
	pos(y, dollars[len(dollars)-1]) // our pos
}

// cast is used to pull out the parser run-specific struct we store our AST in.
// this is usually called in the lexer.
func (yylex *Lexer) cast() *lexParseAST {
	return yylex.parseResult.(*lexParseAST)
}

// pos is a helper function used to track the position in the lexer.
func (yylex *Lexer) pos(lval *yySymType) {
	lval.row = yylex.Line()
	lval.col = yylex.Column()
	// TODO: we could use: `s := yylex.Text()` to calculate a delta length!
	//log.Printf("lexer: %d x %d", lval.row, lval.col)
}

// Error is the error handler which gets called on a parsing error.
func (yylex *Lexer) Error(str string) {
	lp := yylex.cast()
	if str != "" {
		// This error came from the parser. It is usually also set when
		// the lexer fails, because it ends up generating ERROR tokens,
		// which most parsers usually don't match and store in the AST.
		err := ErrParseError // TODO: add more specific types...
		if strings.HasSuffix(str, ErrParseAdditionalEquals.Error()) {
			err = ErrParseAdditionalEquals
		} else if strings.HasSuffix(str, ErrParseExpectingComma.Error()) {
			err = ErrParseExpectingComma
		} else if strings.HasPrefix(str, ErrParseSetType.Error()) {
			err = ErrParseSetType
		}
		lp.parseErr = &LexParseErr{
			Err: err,
			Str: str,
			// FIXME: get these values, by tracking pos in parser...
			// FIXME: currently, the values we get are mostly wrong!
			Row: lp.row, //lp.row[len(lp.row)-1],
			Col: lp.col, //lp.col[len(lp.col)-1],
		}
	}
}

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 132,
	47, 0,
	48, 0,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	-2, 55,
	-1, 133,
	47, 0,
	48, 0,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	-2, 56,
	-1, 134,
	47, 0,
	48, 0,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	-2, 57,
	-1, 135,
	47, 0,
	48, 0,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	-2, 58,
	-1, 136,
	47, 0,
	48, 0,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	-2, 59,
	-1, 137,
	47, 0,
	48, 0,
	49, 0,
	50, 0,
	51, 0,
	52, 0,
	-2, 60,
	-1, 142,
	58, 0,
	-2, 68,
}

const yyPrivate = 57344

const yyLast = 1224

var yyAct = [...]int16{
	118, 24, 175, 172, 23, 157, 16, 117, 88, 156,
	26, 200, 176, 199, 2, 88, 88, 50, 51, 68,
	46, 20, 42, 166, 241, 110, 89, 49, 126, 57,
	48, 226, 25, 89, 89, 71, 269, 54, 92, 93,
	264, 251, 72, 167, 88, 100, 191, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 111, 90, 173,
	76, 77, 78, 79, 165, 90, 90, 213, 141, 120,
	102, 108, 122, 124, 125, 121, 193, 128, 129, 130,
	131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
	127, 142, 98, 123, 90, 148, 151, 222, 223, 143,
	98, 22, 88, 52, 97, 153, 109, 155, 158, 70,
	159, 160, 158, 168, 158, 161, 164, 163, 88, 154,
	89, 162, 285, 177, 248, 98, 169, 170, 247, 246,
	300, 232, 228, 301, 206, 186, 89, 106, 205, 107,
	182, 298, 282, 104, 103, 188, 21, 254, 112, 78,
	79, 207, 90, 74, 69, 86, 87, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 181, 90, 55,
	113, 198, 73, 62, 227, 209, 204, 116, 105, 212,
	74, 101, 224, 225, 21, 74, 208, 229, 210, 178,
	211, 231, 203, 58, 59, 60, 61, 63, 64, 66,
	236, 237, 65, 235, 158, 197, 201, 196, 195, 234,
	194, 243, 187, 245, 239, 179, 18, 177, 242, 197,
	197, 178, 244, 178, 99, 178, 91, 67, 178, 253,
	53, 265, 271, 256, 257, 262, 258, 252, 240, 261,
	115, 114, 96, 174, 171, 19, 221, 266, 268, 122,
	220, 219, 267, 88, 218, 263, 217, 216, 215, 274,
	214, 180, 43, 278, 192, 284, 152, 270, 283, 150,
	95, 89, 287, 147, 275, 276, 94, 36, 35, 34,
	33, 32, 292, 31, 294, 122, 295, 8, 293, 7,
	86, 87, 82, 83, 84, 85, 80, 81, 76, 77,
	78, 79, 302, 90, 88, 6, 5, 3, 1, 0,
	0, 0, 0, 0, 0, 0, 280, 0, 88, 281,
	0, 0, 89, 0, 0, 0, 0, 0, 0, 0,
	303, 0, 0, 0, 0, 0, 89, 0, 0, 0,
	0, 86, 87, 82, 83, 84, 85, 80, 81, 76,
	77, 78, 79, 0, 90, 86, 87, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 88, 90, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 299,
	0, 88, 0, 0, 0, 89, 0, 0, 0, 0,
	0, 0, 0, 297, 0, 296, 0, 0, 88, 89,
	0, 0, 0, 0, 86, 87, 82, 83, 84, 85,
	80, 81, 76, 77, 78, 79, 89, 90, 86, 87,
	82, 83, 84, 85, 80, 81, 76, 77, 78, 79,
	291, 90, 0, 88, 62, 86, 87, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 288, 90, 0,
	88, 89, 0, 0, 58, 59, 60, 61, 63, 64,
	66, 277, 0, 65, 88, 0, 0, 0, 89, 0,
	86, 87, 82, 83, 84, 85, 80, 81, 76, 77,
	78, 79, 89, 90, 0, 0, 0, 86, 87, 82,
	83, 84, 85, 80, 81, 76, 77, 78, 79, 0,
	90, 86, 87, 82, 83, 84, 85, 80, 81, 76,
	77, 78, 79, 273, 90, 62, 88, 0, 0, 0,
	0, 0, 0, 0, 0, 56, 0, 0, 0, 0,
	88, 0, 0, 0, 89, 58, 59, 60, 61, 63,
	64, 66, 272, 260, 65, 0, 0, 88, 89, 0,
	0, 0, 0, 86, 87, 82, 83, 84, 85, 80,
	81, 76, 77, 78, 79, 89, 90, 86, 87, 82,
	83, 84, 85, 80, 81, 76, 77, 78, 79, 259,
	90, 0, 0, 88, 86, 87, 82, 83, 84, 85,
	80, 81, 76, 77, 78, 79, 0, 90, 88, 0,
	0, 89, 0, 0, 0, 0, 0, 0, 0, 0,
	255, 0, 0, 0, 88, 250, 89, 0, 0, 0,
	86, 87, 82, 83, 84, 85, 80, 81, 76, 77,
	78, 79, 89, 90, 0, 86, 87, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 0, 90, 88,
	249, 86, 87, 82, 83, 84, 85, 80, 81, 76,
	77, 78, 79, 230, 90, 0, 88, 89, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 88, 89, 0, 86, 87, 82, 83,
	84, 85, 80, 81, 76, 77, 78, 79, 0, 90,
	190, 89, 0, 86, 87, 82, 83, 84, 85, 80,
	81, 76, 77, 78, 79, 0, 90, 88, 185, 0,
	86, 87, 82, 83, 84, 85, 80, 81, 76, 77,
	78, 79, 88, 90, 0, 89, 0, 0, 0, 0,
	0, 0, 0, 0, 189, 0, 0, 0, 88, 183,
	89, 0, 0, 0, 86, 87, 82, 83, 84, 85,
	80, 81, 76, 77, 78, 79, 89, 90, 0, 86,
	87, 82, 83, 84, 85, 80, 81, 76, 77, 78,
	79, 0, 90, 145, 88, 86, 87, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 144, 90, 0,
	0, 88, 89, 0, 0, 0, 0, 0, 0, 0,
	0, 119, 0, 0, 0, 88, 0, 0, 0, 89,
	0, 86, 87, 82, 83, 84, 85, 80, 81, 76,
	77, 78, 79, 89, 90, 0, 0, 0, 86, 87,
	82, 83, 84, 85, 80, 81, 76, 77, 78, 79,
	0, 90, 86, 87, 82, 83, 84, 85, 80, 81,
	76, 77, 78, 79, 75, 90, 0, 9, 88, 10,
	11, 0, 0, 0, 0, 0, 21, 0, 0, 0,
	0, 0, 88, 0, 0, 0, 89, 0, 0, 0,
	0, 0, 22, 25, 12, 13, 14, 15, 0, 4,
	89, 17, 0, 0, 0, 86, 87, 82, 83, 84,
	85, 80, 81, 76, 77, 78, 79, 0, 90, 86,
	87, 82, 83, 84, 85, 80, 81, 76, 77, 78,
	79, 40, 90, 38, 0, 39, 0, 37, 0, 0,
	0, 27, 28, 29, 30, 0, 47, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 49,
	41, 0, 48, 25, 45, 40, 149, 38, 0, 39,
	0, 37, 0, 0, 0, 27, 28, 29, 30, 0,
	47, 0, 0, 0, 44, 0, 0, 238, 0, 0,
	0, 62, 0, 49, 41, 40, 48, 38, 45, 39,
	146, 37, 0, 0, 0, 27, 28, 29, 30, 0,
	47, 58, 59, 60, 61, 63, 64, 66, 44, 0,
	65, 0, 0, 49, 41, 40, 48, 38, 45, 39,
	0, 37, 0, 0, 0, 27, 28, 29, 30, 0,
	47, 0, 69, 0, 0, 0, 0, 233, 44, 0,
	0, 62, 0, 49, 41, 40, 48, 38, 45, 39,
	0, 37, 0, 0, 0, 27, 28, 29, 30, 0,
	47, 58, 59, 60, 61, 63, 64, 66, 44, 0,
	65, 0, 290, 49, 41, 0, 48, 9, 45, 10,
	11, 0, 289, 0, 0, 0, 21, 9, 0, 10,
	11, 0, 0, 0, 0, 0, 21, 0, 44, 0,
	0, 0, 22, 25, 12, 13, 14, 15, 0, 4,
	0, 17, 22, 25, 12, 13, 14, 15, 286, 4,
	0, 17, 0, 9, 0, 10, 11, 0, 279, 0,
	0, 0, 21, 9, 0, 10, 11, 0, 0, 0,
	0, 0, 21, 0, 0, 0, 0, 0, 22, 25,
	12, 13, 14, 15, 0, 4, 0, 17, 22, 25,
	12, 13, 14, 15, 202, 4, 0, 17, 0, 9,
	0, 10, 11, 0, 184, 0, 0, 0, 21, 9,
	0, 10, 11, 0, 0, 0, 0, 0, 21, 0,
	0, 0, 0, 0, 22, 25, 12, 13, 14, 15,
	0, 4, 0, 17, 22, 25, 12, 13, 14, 15,
	0, 4, 0, 17,
}

var yyPact = [...]int16{
	-1000, -1000, 857, -1000, -1000, -1000, -1000, -1000, -1000, 1051,
	127, 127, 68, 66, -5, 154, 507, 221, 1021, 83,
	9, -5, -1000, -1000, 164, -1000, 860, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 220, 1051, 1051, -1000,
	-1000, 238, 98, 218, 1051, 175, -1000, -5, -1000, -1000,
	124, 123, 172, 133, 65, -16, 1051, 130, -1000, -1000,
	-1000, -1000, 161, 237, 236, 171, -1000, 1051, 807, 34,
	-4, -4, -1000, 1051, -8, -1000, 1051, 1051, 1051, 1051,
	1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 33,
	1051, 1051, 793, 776, 991, 961, -1000, 1051, -5, 1051,
	8, 127, 73, 127, 127, 127, -1000, 127, 1051, 29,
	-12, 874, 1051, 426, 426, 24, 165, 208, 874, -1000,
	-1000, -1000, 159, -1000, 132, 740, -1000, 1179, 94, 94,
	8, 8, 7, 7, 7, 7, 7, 7, 0, 0,
	709, 111, -1000, 205, 1051, -1000, -1000, -1000, 724, -1000,
	-1000, 675, 41, 203, -1000, 201, 200, -1000, 426, -45,
	-47, 199, 1169, 185, 169, -1000, -1000, -1000, 874, -1000,
	117, 129, -1000, 426, 168, -1000, -1000, 426, 1051, -1000,
	62, 1051, 1051, 4, 163, 108, 1051, -1000, 658, -1000,
	1051, -1000, -1000, 106, -1000, -1000, 1043, 127, -1000, 1051,
	1051, 983, -1000, 234, -17, 426, -1000, 24, -1000, 426,
	165, -1000, 874, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 104, 103, 641, 606, 6, 233, 1051, 36,
	136, 590, 1051, 1051, 232, -1000, 575, 539, 1051, 231,
	-1000, 5, 226, -1000, -1000, -1000, 1051, 927, 1, -1000,
	4, -1000, -1000, 36, 228, -1000, 522, 508, 1051, -1000,
	-1000, 456, 1051, 1133, -1000, -1000, 296, 122, 245, 97,
	1123, 1051, -1000, -1000, 442, 1087, 1077, -1000, 425, -1000,
	-1000, 1051, -1000, 927, -1000, 1051, -1000, 390, -1000, -1000,
	-1000, -1000, 373, 121, 359, 110, -1000, -1000, -1000, -1000,
	-1000, 1051, 310, -1000,
}

var yyPgo = [...]int16{
	0, 308, 14, 307, 306, 305, 289, 287, 0, 6,
	9, 12, 216, 22, 7, 283, 281, 280, 279, 278,
	277, 276, 273, 270, 269, 266, 264, 262, 5, 261,
	260, 258, 257, 256, 254, 251, 250, 246, 4, 245,
	21, 1, 244, 243, 3, 2, 20,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 15, 21, 21, 22,
	16, 23, 23, 24, 17, 25, 25, 26, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 14,
	14, 14, 19, 20, 20, 10, 10, 10, 28, 28,
	4, 4, 5, 6, 29, 29, 29, 29, 29, 29,
	29, 29, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 7, 7, 39, 39, 38, 40, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 42, 42, 42, 44,
	43, 43, 43, 45, 45, 46, 46, 9, 12, 12,
	13, 13, 27, 41, 41,
}

var yyR2 = [...]int8{
	0, 1, 0, 2, 1, 1, 1, 1, 1, 5,
	9, 9, 9, 8, 9, 5, 8, 2, 5, 4,
	7, 2, 4, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 9, 3, 3, 0, 2, 2,
	3, 0, 2, 4, 4, 0, 2, 4, 4, 4,
	4, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 2, 4, 6, 3, 5, 3, 0,
	3, 1, 1, 7, 8, 0, 3, 1, 1, 2,
	3, 4, 4, 5, 0, 2, 2, 2, 2, 2,
	2, 2, 2, 4, 6, 4, 6, 6, 8, 4,
	6, 1, 3, 1, 3, 4, 6, 1, 1, 1,
	1, 3, 6, 4, 5, 1, 0, 3, 1, 2,
	0, 3, 1, 1, 2, 1, 1, 2, 1, 3,
	1, 3, 2, 1, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 42, -4, -5, -6, -7, 10,
	12, 13, 37, 38, 39, 40, -9, 44, -12, -39,
	-40, 19, 35, -38, -41, 36, -8, 14, 15, 16,
	17, -15, -16, -17, -18, -19, -20, 10, 6, 8,
	4, 33, -13, -27, 57, 37, -46, 19, 35, 32,
	-9, -9, 35, -12, -13, 15, 18, -11, 28, 29,
	30, 31, 8, 32, 33, 37, 34, 6, -8, 21,
	26, 26, -46, 8, 21, 4, 53, 54, 55, 56,
	51, 52, 47, 48, 49, 50, 45, 46, 8, 26,
	58, 6, -8, -8, -21, -23, 4, 6, 27, 6,
	-8, 6, -13, 20, 20, 6, 4, 6, 6, 41,
	41, -8, 18, 9, 4, 4, 6, -14, -8, 4,
	35, -38, -41, -40, -41, -8, 36, -2, -8, -8,
	-8, -8, -8, -8, -8, -8, -8, -8, -8, -8,
	-8, 35, -8, -14, 4, 7, 9, -22, -8, 5,
	-24, -8, -25, -14, -46, -14, -10, -28, -9, -9,
	-9, -10, -2, -10, -14, 35, 35, 55, -8, -11,
	-11, -42, -44, 35, -43, -45, -11, -9, 20, 7,
	-29, 8, 8, 9, 5, 9, 24, 7, -8, 20,
	25, 5, -26, 35, 7, 7, 7, 20, -11, 58,
	58, 7, 5, 7, 7, 21, 5, 22, -11, 7,
	20, -11, -8, 5, -30, -31, -32, -33, -34, -35,
	-36, -37, 35, 36, -8, -8, 27, 11, 24, -8,
	5, -8, 25, 4, -11, -28, -8, -8, 4, -11,
	4, 41, -11, -44, -11, -45, 25, 25, 21, 9,
	9, 35, 4, -8, 11, 20, -8, -8, 4, 4,
	4, -8, 4, -2, 35, 5, -8, -38, -8, 35,
	-2, 4, 20, 5, -8, -2, -2, 5, -8, 5,
	20, 23, 20, 23, 20, 25, 5, -8, 5, 5,
	5, 5, -8, -38, -8, -8, 5, 20, 20, 20,
	20, 23, -8, 20,
}

var yyDef = [...]int16{
	2, -2, 1, 3, 4, 5, 6, 7, 8, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 101,
	0, 0, 128, 103, 0, 133, 0, 24, 25, 26,
	27, 28, 29, 30, 31, 32, 33, 0, 0, 37,
	41, 0, 0, 72, 0, 0, 130, 0, 125, 126,
	0, 0, 0, 0, 17, 21, 0, 0, 107, 108,
	109, 110, 0, 0, 0, 0, 115, 69, 0, 0,
	0, 0, 127, 0, 0, 2, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 69, 0, 0, 0, 0, 45, 69, 0, 69,
	63, 75, 132, 0, 0, 75, 2, 75, 69, 0,
	0, 80, 0, 0, 0, 116, 120, 0, 71, 84,
	129, 104, 0, 102, 0, 0, 134, 0, 51, 52,
	53, 54, -2, -2, -2, -2, -2, -2, 61, 62,
	0, 66, -2, 0, 0, 35, 36, 38, 0, 40,
	42, 0, 0, 0, 131, 0, 0, 77, 78, 0,
	0, 0, 0, 0, 0, 19, 22, 23, 81, 111,
	0, 0, 118, 0, 0, 122, 123, 0, 0, 82,
	0, 0, 0, 105, 9, 64, 0, 50, 0, 39,
	0, 44, 46, 0, 48, 49, 0, 0, 79, 0,
	0, 0, 15, 0, 18, 0, 113, 0, 119, 0,
	0, 124, 70, 83, 85, 86, 87, 88, 89, 90,
	91, 92, 0, 0, 0, 0, 0, 0, 0, 67,
	0, 0, 0, 0, 0, 76, 0, 0, 0, 0,
	2, 0, 0, 117, 114, 121, 0, 0, 0, 105,
	0, 106, 2, 65, 0, 43, 0, 0, 0, 2,
	2, 0, 0, 0, 20, 112, 0, 0, 0, 0,
	0, 0, 47, 73, 0, 0, 0, 13, 0, 16,
	93, 0, 95, 0, 99, 0, 10, 0, 74, 11,
	12, 14, 0, 0, 0, 0, 34, 94, 96, 100,
	97, 0, 0, 98,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{
	{266, 5, errstrParseExpectingComma},
	{266, 5, errstrParseExpectingComma},
	{266, 5, errstrParseExpectingComma},
	{266, 5, errstrParseExpectingComma},
	{16, 51, errstrParseAdditionalEquals},
	{16, 51, errstrParseAdditionalEquals},
	{16, 51, errstrParseAdditionalEquals},
	{16, 51, errstrParseAdditionalEquals},
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:139
		{
			posLast(yylex, yyDollar) // our pos
			// store the AST in the struct that we previously passed in
			lp := cast(yylex)
			lp.ast = yyDollar[1].stmt
			// this is equivalent to:
			//lp := yylex.(*Lexer).parseResult
			//lp.(*lexParseAST).ast = $1.stmt
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:151
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.stmt = &ast.StmtProg{
				Body: []interfaces.Stmt{},
			}
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:158
		{
			posLast(yylex, yyDollar) // our pos
			// TODO: should we just skip comments for now?
			//if _, ok := $2.stmt.(*ast.StmtComment); !ok {
			//}
			if stmt, ok := yyDollar[1].stmt.(*ast.StmtProg); ok {
				stmts := stmt.Body
				stmts = append(stmts, yyDollar[2].stmt)
				yyVAL.stmt = &ast.StmtProg{
					Body: stmts,
				}
				locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:175
		{
			yyVAL.stmt = &ast.StmtComment{
				Value: yyDollar[1].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:182
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:187
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:192
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:197
		{
			yyVAL.stmt = yyDollar[1].stmt
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:202
		{
			yyVAL.stmt = &ast.StmtIf{
				Condition:  yyDollar[2].expr,
				ThenBranch: yyDollar[4].stmt,
				//ElseBranch: nil,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 10:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:211
		{
			yyVAL.stmt = &ast.StmtIf{
				Condition:  yyDollar[2].expr,
				ThenBranch: yyDollar[4].stmt,
				ElseBranch: yyDollar[8].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 11:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:222
		{
			yyVAL.stmt = &ast.StmtFor{
				Index: yyDollar[2].str,  // no $ prefix
				Value: yyDollar[4].str,  // no $ prefix
				Expr:  yyDollar[6].expr, // XXX: name this List ?
				Body:  yyDollar[8].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 12:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:234
		{
			yyVAL.stmt = &ast.StmtForKV{
				Key:  yyDollar[2].str,  // no $ prefix
				Val:  yyDollar[4].str,  // no $ prefix
				Expr: yyDollar[6].expr, // XXX: name this Map ?
				Body: yyDollar[8].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 13:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:248
		{
			yyVAL.stmt = &ast.StmtFunc{
				Name: yyDollar[2].str,
				Func: &ast.ExprFunc{
					Args: yyDollar[4].args,
					//Return: nil,
					Body: yyDollar[7].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 14:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:261
		{
			fn := &ast.ExprFunc{
				Args:   yyDollar[4].args,
				Return: yyDollar[6].typ, // return type is known
				Body:   yyDollar[8].expr,
			}
			isFullyTyped := yyDollar[6].typ != nil // true if set
			m := make(map[string]*types.Type)
			ord := []string{}
			for _, a := range yyDollar[4].args {
				if a.Type == nil {
					// at least one is unknown, can't run SetType...
					isFullyTyped = false
					break
				}
				m[a.Name] = a.Type
				ord = append(ord, a.Name)
			}
			var typ *types.Type
			if isFullyTyped {
				typ = &types.Type{
					Kind: types.KindFunc,
					Map:  m,
					Ord:  ord,
					Out:  yyDollar[6].typ,
				}
				// XXX: We might still need to do this for now...
				if err := fn.SetType(typ); err != nil {
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
				}
			}
			yyVAL.stmt = &ast.StmtFunc{
				Name: yyDollar[2].str,
				Func: fn,
				Type: typ, // sam says add the type here instead...
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:302
		{
			yyVAL.stmt = &ast.StmtClass{
				Name: yyDollar[2].str,
				Args: nil,
				Body: yyDollar[4].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 16:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:313
		{
			yyVAL.stmt = &ast.StmtClass{
				Name: yyDollar[2].str,
				Args: yyDollar[4].args,
				Body: yyDollar[7].stmt,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:323
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name: yyDollar[2].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:331
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name: yyDollar[2].str,
				Args: yyDollar[4].exprs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:341
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name:  yyDollar[2].str,
				Alias: yyDollar[4].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 20:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:351
		{
			yyVAL.stmt = &ast.StmtInclude{
				Name:  yyDollar[2].str,
				Args:  yyDollar[4].exprs,
				Alias: yyDollar[7].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:361
		{
			yyVAL.stmt = &ast.StmtImport{
				Name: yyDollar[2].str,
				//Alias: "",
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:370
		{
			yyVAL.stmt = &ast.StmtImport{
				Name:  yyDollar[2].str,
				Alias: yyDollar[4].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:379
		{
			yyVAL.stmt = &ast.StmtImport{
				Name:  yyDollar[2].str,
				Alias: yyDollar[4].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:397
		{
			yyVAL.expr = &ast.ExprBool{
				V: yyDollar[1].bool,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:404
		{
			yyVAL.expr = &ast.ExprStr{
				V: yyDollar[1].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:411
		{
			yyVAL.expr = &ast.ExprInt{
				V: yyDollar[1].int,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:418
		{
			yyVAL.expr = &ast.ExprFloat{
				V: yyDollar[1].float,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:425
		{
			// TODO: list could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:431
		{
			// TODO: map could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:437
		{
			// TODO: struct could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:443
		{
			// TODO: call could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:449
		{
			// TODO: var could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:455
		{
			// TODO: var could be squashed in here directly...
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 34:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/parser.y:461
		{
			yyVAL.expr = &ast.ExprIf{
				Condition:  yyDollar[2].expr,
				ThenBranch: yyDollar[4].expr,
				ElseBranch: yyDollar[8].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:471
		{
			yyVAL.expr = yyDollar[2].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:479
		{
			yyVAL.expr = &ast.ExprList{
				Elements: yyDollar[2].exprs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:488
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = []interfaces.Expr{}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:493
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[2].expr)
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:500
		{
			yyVAL.expr = yyDollar[1].expr
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:508
		{
			yyVAL.expr = &ast.ExprMap{
				KVs: yyDollar[2].mapKVs,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:517
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = []*ast.ExprMapKV{}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:522
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKVs = append(yyDollar[1].mapKVs, yyDollar[2].mapKV)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:529
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.mapKV = &ast.ExprMapKV{
				Key: yyDollar[1].expr,
				Val: yyDollar[3].expr,
			}
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:540
		{
			yyVAL.expr = &ast.ExprStruct{
				Fields: yyDollar[3].structFields,
			}
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:548
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = []*ast.ExprStructField{}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:553
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structFields = append(yyDollar[1].structFields, yyDollar[2].structField)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:560
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.structField = &ast.ExprStructField{
				Name:  yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:572
		{
			yyVAL.expr = &ast.ExprCall{
				Name: yyDollar[1].str,
				Args: yyDollar[3].exprs,
				//Var: false, // default
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:583
		{
			yyVAL.expr = &ast.ExprCall{
				Name: yyDollar[1].str,
				Args: yyDollar[3].exprs,
				// Instead of `Var: true`, we could have added a `$`
				// prefix to the Name, but I felt this was more elegant.
				Var: true, // lambda
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:595
		{
			yyVAL.expr = &ast.ExprCall{
				Name: "", // anonymous!
				Args: yyDollar[3].exprs,
				Anon: yyDollar[1].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:604
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str, // for PLUS this is a `+` character
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:618
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:632
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:646
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:660
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:674
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:688
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:702
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:716
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:730
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:744
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:758
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[2].str,
					},
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:772
		{
			yyVAL.expr = &ast.ExprCall{
				Name: operators.OperatorFuncName,
				Args: []interfaces.Expr{
					&ast.ExprStr{ // operator first
						V: yyDollar[1].str,
					},
					yyDollar[2].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 64:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:788
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.LookupFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the list or map
					yyDollar[3].expr, // the index or key is an expr
					//$6.expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 65:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:803
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.LookupDefaultFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the list or map
					yyDollar[3].expr, // the index or key is an expr
					yyDollar[6].expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:818
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.StructLookupFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the struct
					&ast.ExprStr{
						V: yyDollar[3].str, // the field is always an str
					},
					//$5.expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 67:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:835
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.StructLookupOptionalFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr, // the struct
					&ast.ExprStr{
						V: yyDollar[3].str, // the field is always an str
					},
					yyDollar[5].expr, // the default
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:849
		{
			yyVAL.expr = &ast.ExprCall{
				Name: funcs.ContainsFuncName,
				Args: []interfaces.Expr{
					yyDollar[1].expr,
					yyDollar[3].expr,
				},
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 69:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:864
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = []interfaces.Expr{}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:870
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:875
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.exprs = append([]interfaces.Expr{}, yyDollar[1].expr)
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:882
		{
			yyVAL.expr = &ast.ExprVar{
				Name: yyDollar[1].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 73:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:895
		{
			yyVAL.expr = &ast.ExprFunc{
				Args: yyDollar[3].args,
				//Return: nil,
				Body: yyDollar[6].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 74:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:905
		{
			yyVAL.expr = &ast.ExprFunc{
				Args:   yyDollar[3].args,
				Return: yyDollar[5].typ, // return type is known
				Body:   yyDollar[7].expr,
			}
			isFullyTyped := yyDollar[5].typ != nil // true if set
			m := make(map[string]*types.Type)
			ord := []string{}
			for _, a := range yyDollar[3].args {
				if a.Type == nil {
					// at least one is unknown, can't run SetType...
					isFullyTyped = false
					break
				}
				m[a.Name] = a.Type
				ord = append(ord, a.Name)
			}
			if isFullyTyped {
				typ := &types.Type{
					Kind: types.KindFunc,
					Map:  m,
					Ord:  ord,
					Out:  yyDollar[5].typ,
				}
				if err := yyVAL.expr.SetType(typ); err != nil {
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
				}
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.expr)
		}
	case 75:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:940
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:945
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].arg)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:950
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append([]*interfaces.Arg{}, yyDollar[1].arg)
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:958
		{
			yyVAL.arg = &interfaces.Arg{
				Name: yyDollar[1].str,
			}
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:965
		{
			yyVAL.arg = &interfaces.Arg{
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:975
		{
			yyVAL.stmt = &ast.StmtBind{
				Ident: yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:985
		{
			var expr interfaces.Expr = yyDollar[4].expr
			// XXX: We still need to do this for now it seems...
			if err := expr.SetType(yyDollar[2].typ); err != nil {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
			}
			yyVAL.stmt = &ast.StmtBind{
				Ident: yyDollar[1].str,
				Value: expr,
				Type:  yyDollar[2].typ, // sam says add the type here instead...
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1007
		{
			call := &ast.ExprCall{
				Name: yyDollar[1].str, // the function name
				Args: yyDollar[3].exprs,
				//Var: false, // default
			}
			name := &ast.ExprStr{
				V: yyDollar[1].str, // any constant, non-empty name
			}
			res := &ast.StmtRes{
				Kind:     interfaces.PanicResKind,
				Name:     name,
				Contents: []ast.StmtResContents{},
			}
			yyVAL.stmt = &ast.StmtIf{
				Condition:  call,
				ThenBranch: res,
				//ElseBranch: nil,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 83:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:1048
		{
			yyVAL.stmt = &ast.StmtRes{
				Kind:     yyDollar[1].str,
				Name:     yyDollar[2].expr,
				Contents: yyDollar[4].resContents,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 84:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1059
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = []ast.StmtResContents{}
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1064
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resField)
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1069
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resField)
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1074
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resEdge)
		}
	case 88:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1079
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resEdge)
		}
	case 89:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1084
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1089
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 91:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1094
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 92:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1099
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.resContents = append(yyDollar[1].resContents, yyDollar[2].resMeta)
		}
	case 93:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1106
		{
			yyVAL.resField = &ast.StmtResField{
				Field: yyDollar[1].str,
				Value: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resField)
		}
	case 94:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1117
		{
			yyVAL.resField = &ast.StmtResField{
				Field:     yyDollar[1].str,
				Value:     yyDollar[5].expr,
				Condition: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resField)
		}
	case 95:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1129
		{
			yyVAL.resEdge = &ast.StmtResEdge{
				Property: yyDollar[1].str,
				EdgeHalf: yyDollar[3].edgeHalf,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resEdge)
		}
	case 96:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1140
		{
			yyVAL.resEdge = &ast.StmtResEdge{
				Property:  yyDollar[1].str,
				EdgeHalf:  yyDollar[5].edgeHalf,
				Condition: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resEdge)
		}
	case 97:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1152
		{
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property: yyDollar[3].str,
				MetaExpr: yyDollar[5].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 98:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/parser.y:1167
		{
			posLast(yylex, yyDollar) // our pos
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property:  yyDollar[3].str,
				MetaExpr:  yyDollar[7].expr,
				Condition: yyDollar[5].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 99:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1184
		{
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property: yyDollar[1].str,
				MetaExpr: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 100:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1199
		{
			if strings.ToLower(yyDollar[1].str) != strings.ToLower(ast.MetaField) {
				// this will ultimately cause a parser error to occur...
				yylex.Error(fmt.Sprintf("%s: %s", ErrParseResFieldInvalid, yyDollar[1].str))
			}
			yyVAL.resMeta = &ast.StmtResMeta{
				Property:  yyDollar[1].str,
				MetaExpr:  yyDollar[5].expr,
				Condition: yyDollar[3].expr,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.resMeta)
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1217
		{
			yyVAL.stmt = &ast.StmtEdge{
				EdgeHalfList: yyDollar[1].edgeHalfList,
				//Notify: false, // unused here
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1226
		{
			yyVAL.stmt = &ast.StmtEdge{
				EdgeHalfList: []*ast.StmtEdgeHalf{
					yyDollar[1].edgeHalf,
					yyDollar[3].edgeHalf,
				},
				//Notify: false, // unused here, it is implied (i think)
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.stmt)
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1239
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.edgeHalfList = []*ast.StmtEdgeHalf{yyDollar[1].edgeHalf}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1244
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.edgeHalfList = append(yyDollar[1].edgeHalfList, yyDollar[3].edgeHalf)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1252
		{
			yyVAL.edgeHalf = &ast.StmtEdgeHalf{
				Kind: yyDollar[1].str,
				Name: yyDollar[3].expr,
				//SendRecv: "", // unused
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.edgeHalf)
		}
	case 106:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1264
		{
			yyVAL.edgeHalf = &ast.StmtEdgeHalf{
				Kind:     yyDollar[1].str,
				Name:     yyDollar[3].expr,
				SendRecv: yyDollar[6].str,
			}
			locate(yylex, yyDollar[1], yyDollar[len(yyDollar)-1], yyVAL.edgeHalf)
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1275
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "bool"
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1280
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "str"
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1285
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "int"
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1290
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "float"
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1296
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.typ = types.NewType("[]" + yyDollar[3].typ.String())
		}
	case 112:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:1302
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.typ = types.NewType(fmt.Sprintf("map{%s: %s}", yyDollar[3].typ.String(), yyDollar[5].typ.String()))
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:1308
		{
			posLast(yylex, yyDollar) // our pos

			names := make(map[string]struct{})
			strs := []string{}
			for _, arg := range yyDollar[3].args {
				s := fmt.Sprintf("%s %s", arg.Name, arg.Type.String())
				if _, exists := names[arg.Name]; exists {
					// duplicate field name used
					err := fmt.Errorf("duplicate struct field of `%s`", s)
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
					break // we must skip, because code continues!
				}
				names[arg.Name] = struct{}{}
				strs = append(strs, s)
			}

			yyVAL.typ = types.NewType(fmt.Sprintf("%s{%s}", yyDollar[1].str, strings.Join(strs, "; ")))
		}
	case 114:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/parser.y:1331
		{
			posLast(yylex, yyDollar) // our pos

			m := make(map[string]*types.Type)
			ord := []string{}
			for i, a := range yyDollar[3].args {
				if a.Type == nil {
					// at least one is unknown, can't run SetType...
					// this means there is a programming error here!
					err := fmt.Errorf("type is unspecified for arg #%d", i)
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
					break // safety
				}
				name := a.Name
				if name == "" {
					name = util.NumToAlpha(i) // if unspecified...
				}
				if util.StrInList(name, ord) {
					// duplicate arg name used
					err := fmt.Errorf("duplicate arg name of `%s`", name)
					// this will ultimately cause a parser error to occur...
					yylex.Error(fmt.Sprintf("%s: %+v", ErrParseSetType, err))
					break // safety
				}
				m[name] = a.Type
				ord = append(ord, name)
			}

			yyVAL.typ = &types.Type{
				Kind: types.KindFunc,
				Map:  m,
				Ord:  ord,
				Out:  yyDollar[5].typ,
			}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1368
		{
			posLast(yylex, yyDollar)                   // our pos
			yyVAL.typ = types.NewType(yyDollar[1].str) // "variant"
		}
	case 116:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1375
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1380
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].arg)
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1385
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append([]*interfaces.Arg{}, yyDollar[1].arg)
		}
	case 119:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1392
		{
			posLast(yylex, yyDollar)     // our pos
			yyVAL.arg = &interfaces.Arg{ // reuse the Arg struct
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 120:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:1402
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = []*interfaces.Arg{}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1407
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append(yyDollar[1].args, yyDollar[3].arg)
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1412
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.args = append([]*interfaces.Arg{}, yyDollar[1].arg)
			//$$.args = []*interfaces.Arg{$1.arg} // TODO: is this equivalent?
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1421
		{
			yyVAL.arg = &interfaces.Arg{
				Type: yyDollar[1].typ,
			}
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1429
		{
			yyVAL.arg = &interfaces.Arg{
				Name: yyDollar[1].str,
				Type: yyDollar[2].typ,
			}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1438
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1444
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 127:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1452
		{
			posLast(yylex, yyDollar)    // our pos
			yyVAL.str = yyDollar[2].str // don't include the leading $
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1460
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1466
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str + yyDollar[2].str + yyDollar[3].str
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1473
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1478
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str + interfaces.ModuleSep + yyDollar[3].str
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:1487
		{
			posLast(yylex, yyDollar)    // our pos
			yyVAL.str = yyDollar[2].str // don't include the leading $
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:1494
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:1499
		{
			posLast(yylex, yyDollar) // our pos
			yyVAL.str = yyDollar[1].str + yyDollar[2].str + yyDollar[3].str
		}
	}
	goto yystack /* stack new state and value */
}
